[functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**/*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  PUBLIC_BUILD_START_TIME = "$(date +%s)"
  npm_config_target_platform = "linux"
  npm_config_target_arch = "x64"
  npm_config_cache = "/opt/buildhome/.npm"

[build]
  command = "yarn cache clean && yarn add sharp --ignore-engines && yarn run build"
  
[[redirects]]
  from = "/wp-content/*"
  to = "https://backend.gymtonic.sg/wp-content/:splat"
  status = 200
  force = true
