[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  PUBLIC_BUILD_START_TIME = "$(date +%s)"
  
[[redirects]]
  from = "/wp-content/*"
  to = "https://backend.gymtonic.sg/wp-content/:splat"
  status = 200
  force = true

[functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**/*"]
